# Generated by Django 4.0.5 on 2022-06-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='principla_image',
            new_name='principal_image',
        ),
    ]
